In [1]:
import glob
import json
import os
import pandas as pd
import random

import initialise
import common
from analysis_utils import calc_statistics, sort_file_list
from display_utils import display_frames
from model_utils import generate_ensembles

In [2]:
samples_file_europe = os.path.join(common.DATASETS_DIR, 'europe_samples_365days.csv')
models_dir = r'Z:\LFMC_data\Transfer_learning\Models'  # common.MODELS_DIR # 
#model_dir = os.path.join(models_dir, 'europe_2013_models')
model_dir = os.path.join(models_dir, 'europe_2013_epochs')
precision = 3       # floating point precision for saved predictions

In [3]:
with open(os.path.join(model_dir, 'experiment.json'), 'r') as f:
    experiment = json.load(f)
test_names = [x['testName'] for x in experiment['tests']]
test_names

['Europe only - all data',
 'Europe only - 4000 samples',
 'Europe only - 3000 samples',
 'Europe only - 2000 samples',
 'Europe only - 1000 samples',
 'Europe only - 750 samples',
 'Europe only - 500 samples',
 'Europe only - 400 samples',
 'Europe only - 300 samples',
 'Europe only - 200 samples',
 'Europe only - 100 samples',
 'Europe pretrained - all data',
 'Europe pretrained - 4000 samples',
 'Europe pretrained - 3000 samples',
 'Europe pretrained - 2000 samples',
 'Europe pretrained - 1000 samples',
 'Europe pretrained - 750 samples',
 'Europe pretrained - 500 samples',
 'Europe pretrained - 400 samples',
 'Europe pretrained - 300 samples',
 'Europe pretrained - 200 samples',
 'Europe pretrained - 100 samples',
 'Europe frozen layers - all data',
 'Europe frozen layers - 4000 samples',
 'Europe frozen layers - 3000 samples',
 'Europe frozen layers - 2000 samples',
 'Europe frozen layers - 1000 samples',
 'Europe frozen layers - 750 samples',
 'Europe frozen layers - 500 samples',
 'Europe frozen layers - 400 samples',
 'Europe frozen layers - 300 samples',
 'Europe frozen layers - 200 samples',
 'Europe frozen layers - 100 samples']

In [4]:
preds = []
test_dirs = sort_file_list(glob.glob(os.path.join(model_dir, f'test*')), 'test')
for test_dir in test_dirs[0:11]:
    test_preds = []
    run_dirs = sort_file_list(glob.glob(os.path.join(test_dir, f'run*')), 'run')
    for run_dir in run_dirs:
        run_preds = []
        epoch_dirs = sort_file_list(glob.glob(os.path.join(run_dir, f'epoch*')), 'epoch')
        for epoch_dir in epoch_dirs:
            preds_ = pd.read_csv(os.path.join(epoch_dir, 'test_predicts.csv'), index_col=0)
            run_preds.append(preds_)
        preds_ = pd.read_csv(os.path.join(run_dir, 'test_predicts.csv'), index_col=0)
        run_preds.append(preds_)
        test_preds.append(run_preds)
    preds.append(test_preds)

In [5]:
y = preds_.y
stats_dfs = []
for test_preds in preds: #[:num_ensembles]:
    summ_ = pd.concat([pd.concat([r.base for r in t], keys=pd.RangeIndex.from_range(range(100, 1001, 100))) for t in test_preds],
                      axis=1, ignore_index=True).mean(axis=1).unstack()
    stats_ = {epochs: calc_statistics(y, yhat[y.index]) for epochs, yhat in summ_.iterrows()}
    summ_stats = pd.DataFrame.from_dict(stats_, orient='index')
    stats_dfs.append(summ_stats)
display_frames(stats_dfs, test_names[:11], precision=2)

,Count,RMSE,R2,Bias
100,244,20.13,0.25,-4.09
200,244,20.17,0.24,-4.00
300,244,20.28,0.23,-4.02
400,244,20.28,0.23,-4.00
500,244,20.28,0.23,-3.94
600,244,20.29,0.23,-3.92
700,244,20.26,0.24,-3.87
800,244,20.26,0.24,-3.84
900,244,20.33,0.23,-3.86
1000,244,20.28,0.23,-3.76
,Count,RMSE,R2,Bias
100,244,20.45,0.22,-4.34
200,244,20.51,0.22,-4.14
300,244,20.50,0.22,-4.14
400,244,20.50,0.22,-4.15
500,244,20.51,0.22,-4.09
600,244,20.53,0.22,-4.06
700,244,20.55,0.21,-4.01
800,244,20.55,0.21,-4.01
900,244,20.57,0.21,-4.04
1000,244,20.58,0.21,-4.02
,Count,RMSE,R2,Bias
100,244,20.33,0.23,-4.81
200,244,20.35,0.23,-4.39
300,244,20.47,0.22,-4.53
400,244,20.49,0.22,-4.57
500,244,20.50,0.22,-4.58
600,244,20.50,0.22,-4.58
700,244,20.50,0.22,-4.55
800,244,20.48,0.22,-4.52
900,244,20.48,0.22,-4.48
1000,244,20.47,0.22,-4.47
,Count,RMSE,R2,Bias
100,244,21.06,0.17,-6.48
200,244,20.68,0.20,-4.80
300,244,20.73,0.20,-4.77
400,244,20.74,0.20,-4.78
500,244,20.76,0.20,-4.77
600,244,20.76,0.20,-4.75
700,244,20.74,0.20,-4.69
800,244,20.73,0.20,-4.61
900,244,20.71,0.20,-4.57
1000,244,20.70,0.20,-4.54
,Count,RMSE,R2,Bias
100,244,23.41,-0.02,-11.97
200,244,21.41,0.15,-6.09
300,244,21.19,0.16,-5.15
400,244,21.18,0.16,-5.01
500,244,21.16,0.17,-4.98
600,244,21.15,0.17,-4.97
700,244,21.13,0.17,-4.93
800,244,21.12,0.17,-4.91
900,244,21.10,0.17,-4.91
1000,244,21.09,0.17,-4.87
,Count,RMSE,R2,Bias
100,244,23.51,-0.03,-12.11
200,244,21.57,0.13,-6.57
300,244,21.34,0.15,-5.64
400,244,21.32,0.15,-5.53
500,244,21.33,0.15,-5.50
600,244,21.32,0.15,-5.43
700,244,21.30,0.15,-5.38
800,244,21.30,0.16,-5.35
900,244,21.29,0.16,-5.32
1000,244,21.28,0.16,-5.29
,Count,RMSE,R2,Bias
100,244,26.24,-0.28,-16.55
200,244,23.07,0.01,-11.15
300,244,21.88,0.11,-8.01
400,244,21.50,0.14,-6.72
500,244,21.37,0.15,-6.22
600,244,21.33,0.15,-6.02
700,244,21.31,0.15,-5.94
800,244,21.30,0.15,-5.92
900,244,21.30,0.16,-5.91
1000,244,21.31,0.15,-5.90
,Count,RMSE,R2,Bias
100,244,25.99,-0.26,-16.11
200,244,22.95,0.02,-10.79
300,244,21.97,0.10,-8.12
400,244,21.73,0.12,-7.08
500,244,21.69,0.12,-6.67
600,244,21.67,0.13,-6.50
700,244,21.65,0.13,-6.43
800,244,21.65,0.13,-6.40
900,244,21.65,0.13,-6.40
1000,244,21.64,0.13,-6.38
,Count,RMSE,R2,Bias
100,244,25.47,-0.21,-15.43
200,244,22.66,0.04,-10.50
300,244,21.87,0.11,-8.09
400,244,21.64,0.13,-7.08
500,244,21.57,0.13,-6.68
600,244,21.53,0.14,-6.52
700,244,21.51,0.14,-6.45
800,244,21.50,0.14,-6.42
900,244,21.50,0.14,-6.41
1000,244,21.49,0.14,-6.40
,Count,RMSE,R2,Bias
100,244,25.46,-0.21,-15.34
200,244,23.02,0.01,-11.03
300,244,22.27,0.08,-8.62
400,244,22.09,0.09,-7.57
500,244,22.03,0.10,-7.14
600,244,22.01,0.10,-6.97
700,244,22.00,0.10,-6.90
800,244,21.99,0.10,-6.88
900,244,21.99,0.10,-6.86
1000,244,21.99,0.10,-6.86
,Count,RMSE,R2,Bias
100,244,25.42,-0.20,-14.70
200,244,23.49,-0.03,-11.45
300,244,22.84,0.03,-9.73
400,244,22.70,0.04,-8.98
500,244,22.66,0.04,-8.65
600,244,22.65,0.04,-8.52
700,244,22.64,0.05,-8.47
800,244,22.64,0.05,-8.45
900,244,22.64,0.05,-8.44
1000,244,22.64,0.05,-8.43

In [6]:
preds2 = []
for test_preds in preds:
    temp = []
    for epoch in range(len(test_preds[0])):
        temp.append([])
        for run in range(len(test_preds)):
            temp[-1].append(test_preds[run][epoch])
    preds2.append(temp)

In [7]:
random_seed = 46524

In [8]:
y = preds_.y
full_stats = []
num_ensembles = 100
ensemble_size = 10
for test_preds in preds2:
    summ_stats = []
    ensembles, test_stats = generate_ensembles(test_preds, ensemble_runs=num_ensembles, ensemble_sizes=ensemble_size)
    for epoch_ in test_stats:
        summ_stats.append(pd.concat([x.loc['base'] for x in epoch_], axis=1)) #.mean(axis=1)
    full_stats.append(pd.concat(summ_stats, keys=pd.RangeIndex.from_range(range(100, 1001, 100))).mean(axis=1).unstack())

Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100

In [9]:
display_frames(full_stats, test_names[:11], precision=2)

,Count,RMSE,R2,Bias
100,244.00,20.65,0.21,-4.16
200,244.00,20.59,0.21,-4.06
300,244.00,20.79,0.19,-3.95
400,244.00,20.90,0.19,-4.14
500,244.00,20.83,0.19,-3.98
600,244.00,20.81,0.19,-3.95
700,244.00,20.68,0.20,-3.79
800,244.00,20.68,0.20,-3.80
900,244.00,20.73,0.20,-3.83
1000,244.00,20.70,0.20,-3.78
,Count,RMSE,R2,Bias
100,244.00,20.99,0.18,-4.27
200,244.00,21.01,0.18,-4.11
300,244.00,21.03,0.18,-4.07
400,244.00,21.02,0.18,-4.13
500,244.00,20.99,0.18,-4.14
600,244.00,20.97,0.18,-4.12
700,244.00,21.00,0.18,-4.00
800,244.00,20.95,0.18,-3.96
900,244.00,20.96,0.18,-4.01
1000,244.00,20.95,0.18,-4.06
,Count,RMSE,R2,Bias
100,244.00,20.87,0.19,-4.83
200,244.00,20.87,0.19,-4.34
300,244.00,20.96,0.18,-4.53
400,244.00,21.06,0.17,-4.61
500,244.00,21.02,0.18,-4.62
600,244.00,21.00,0.18,-4.56
700,244.00,20.90,0.19,-4.52
800,244.00,20.85,0.19,-4.50
900,244.00,20.86,0.19,-4.41
1000,244.00,20.80,0.19,-4.50
,Count,RMSE,R2,Bias
100,244.00,21.52,0.14,-6.39
200,244.00,21.25,0.16,-4.77
300,244.00,21.21,0.16,-4.78
400,244.00,21.25,0.16,-4.84
500,244.00,21.30,0.15,-4.76
600,244.00,21.20,0.16,-4.74
700,244.00,21.15,0.17,-4.71
800,244.00,21.09,0.17,-4.60
900,244.00,21.18,0.16,-4.57
1000,244.00,21.04,0.18,-4.51
,Count,RMSE,R2,Bias
100,244.00,23.73,-0.05,-12.06
200,244.00,21.93,0.10,-6.11
300,244.00,21.76,0.12,-5.16
400,244.00,21.79,0.11,-5.07
500,244.00,21.71,0.12,-4.91
600,244.00,21.69,0.12,-4.99
700,244.00,21.62,0.13,-4.95
800,244.00,21.59,0.13,-4.88
900,244.00,21.64,0.13,-4.94
1000,244.00,21.52,0.14,-4.94
,Count,RMSE,R2,Bias
100,244.00,23.74,-0.05,-12.12
200,244.00,22.10,0.09,-6.55
300,244.00,21.87,0.11,-5.65
400,244.00,21.88,0.11,-5.56
500,244.00,21.81,0.11,-5.48
600,244.00,21.82,0.11,-5.43
700,244.00,21.73,0.12,-5.42
800,244.00,21.70,0.12,-5.29
900,244.00,21.68,0.12,-5.36
1000,244.00,21.67,0.13,-5.34
,Count,RMSE,R2,Bias
100,244.00,26.50,-0.31,-16.64
200,244.00,23.39,-0.02,-11.10
300,244.00,22.32,0.07,-8.06
400,244.00,22.06,0.09,-6.66
500,244.00,22.02,0.10,-6.23
600,244.00,21.91,0.11,-5.91
700,244.00,21.89,0.11,-5.94
800,244.00,22.00,0.10,-5.97
900,244.00,21.97,0.10,-6.06
1000,244.00,21.88,0.11,-5.98
,Count,RMSE,R2,Bias
100,244.00,26.20,-0.28,-16.17
200,244.00,23.29,-0.01,-10.77
300,244.00,22.37,0.07,-8.17
400,244.00,22.33,0.07,-7.14
500,244.00,22.37,0.07,-6.74
600,244.00,22.25,0.08,-6.50
700,244.00,22.27,0.08,-6.41
800,244.00,22.36,0.07,-6.36
900,244.00,22.30,0.07,-6.58
1000,244.00,22.21,0.08,-6.39
,Count,RMSE,R2,Bias
100,244.00,25.67,-0.23,-15.46
200,244.00,23.00,0.01,-10.51
300,244.00,22.30,0.07,-8.22
400,244.00,22.22,0.08,-7.09
500,244.00,22.20,0.08,-6.71
600,244.00,22.12,0.09,-6.37
700,244.00,22.13,0.09,-6.36
800,244.00,22.24,0.08,-6.36
900,244.00,22.12,0.09,-6.62
1000,244.00,22.13,0.09,-6.46
,Count,RMSE,R2,Bias
100,244.00,25.64,-0.23,-15.33
200,244.00,23.38,-0.02,-11.02
300,244.00,22.66,0.04,-8.70
400,244.00,22.67,0.04,-7.56
500,244.00,22.67,0.04,-7.09
600,244.00,22.69,0.04,-6.93
700,244.00,22.64,0.05,-6.89
800,244.00,22.69,0.04,-6.79
900,244.00,22.65,0.04,-7.09
1000,244.00,22.67,0.04,-7.00
,Count,RMSE,R2,Bias
100,244.00,25.64,-0.23,-14.72
200,244.00,23.83,-0.06,-11.42
300,244.00,23.30,-0.01,-9.91
400,244.00,23.46,-0.03,-9.02
500,244.00,23.37,-0.02,-8.47
600,244.00,23.47,-0.03,-8.51
700,244.00,23.37,-0.02,-8.50
800,244.00,23.46,-0.03,-8.48
900,244.00,23.34,-0.02,-8.53
1000,244.00,23.28,-0.01,-8.50

## Transfer Learning

In [24]:
preds = []
test_dirs = sort_file_list(glob.glob(os.path.join(model_dir, f'test*')), 'test')
for test_dir in test_dirs[11:22]:
    print(test_dir)
    test_preds = []
    run_dirs = sort_file_list(glob.glob(os.path.join(test_dir, f'run*')), 'run')
    for run_dir in run_dirs:
#        print(run_dir)
        run_preds = []
        epoch_dirs = sort_file_list(glob.glob(os.path.join(run_dir, f'epoch*')), 'epoch')
        for epoch_dir in epoch_dirs:
            preds_ = pd.read_csv(os.path.join(epoch_dir, 'test_predicts.csv'), index_col=0)
            run_preds.append(preds_)
        preds_ = pd.read_csv(os.path.join(run_dir, 'test_predicts.csv'), index_col=0)
        run_preds.append(preds_)
        test_preds.append(run_preds)
    preds.append(test_preds)

Z:\LFMC_data\Transfer_learning\Models\europe_2013_epochs\test11
Z:\LFMC_data\Transfer_learning\Models\europe_2013_epochs\test12
Z:\LFMC_data\Transfer_learning\Models\europe_2013_epochs\test13
Z:\LFMC_data\Transfer_learning\Models\europe_2013_epochs\test14
Z:\LFMC_data\Transfer_learning\Models\europe_2013_epochs\test15
Z:\LFMC_data\Transfer_learning\Models\europe_2013_epochs\test16
Z:\LFMC_data\Transfer_learning\Models\europe_2013_epochs\test17
Z:\LFMC_data\Transfer_learning\Models\europe_2013_epochs\test18
Z:\LFMC_data\Transfer_learning\Models\europe_2013_epochs\test19
Z:\LFMC_data\Transfer_learning\Models\europe_2013_epochs\test20
Z:\LFMC_data\Transfer_learning\Models\europe_2013_epochs\test21

In [25]:
y = preds_.y
stats_dfs = []
for test_preds in preds: #[:num_ensembles]:
    summ_ = pd.concat([pd.concat([r.base for r in t], keys=pd.RangeIndex.from_range(range(0, 1001, 100))) for t in test_preds],
                      axis=1, ignore_index=True).mean(axis=1).unstack()
    stats_ = {epochs: calc_statistics(y, yhat[y.index]) for epochs, yhat in summ_.iterrows()}
    summ_stats = pd.DataFrame.from_dict(stats_, orient='index')
    stats_dfs.append(summ_stats)
display_frames(stats_dfs, test_names[11:22], precision=2)

,Count,RMSE,R2,Bias
0,244,25.99,-0.26,-17.91
100,244,19.41,0.30,-3.88
200,244,19.35,0.30,-3.55
300,244,19.36,0.30,-3.47
400,244,19.38,0.30,-3.27
500,244,19.39,0.30,-3.34
600,244,19.37,0.30,-3.13
700,244,19.39,0.30,-3.22
800,244,19.45,0.30,-3.21
900,244,19.44,0.30,-3.22
1000,244,19.49,0.29,-3.22
,Count,RMSE,R2,Bias
0,244,26.01,-0.26,-17.95
100,244,19.14,0.32,-3.49
200,244,19.03,0.33,-2.93
300,244,19.09,0.32,-2.97
400,244,19.13,0.32,-3.02
500,244,19.19,0.31,-3.04
600,244,19.23,0.31,-3.09
700,244,19.25,0.31,-3.10
800,244,19.29,0.31,-3.14
900,244,19.30,0.31,-3.13
1000,244,19.33,0.30,-3.11
,Count,RMSE,R2,Bias
0,244,26.01,-0.26,-17.98
100,244,19.62,0.28,-4.70
200,244,19.35,0.30,-3.55
300,244,19.35,0.30,-3.44
400,244,19.39,0.30,-3.43
500,244,19.42,0.30,-3.40
600,244,19.45,0.30,-3.37
700,244,19.46,0.29,-3.33
800,244,19.48,0.29,-3.30
900,244,19.50,0.29,-3.25
1000,244,19.49,0.29,-3.19
,Count,RMSE,R2,Bias
0,244,26.11,-0.27,-18.16
100,244,20.56,0.21,-6.35
200,244,19.95,0.26,-3.70
300,244,19.91,0.26,-3.49
400,244,19.89,0.26,-3.43
500,244,19.87,0.26,-3.41
600,244,19.88,0.26,-3.41
700,244,19.88,0.26,-3.40
800,244,19.90,0.26,-3.40
900,244,19.91,0.26,-3.41
1000,244,19.91,0.26,-3.42
,Count,RMSE,R2,Bias
0,244,26.05,-0.26,-18.03
100,244,23.75,-0.05,-13.12
200,244,20.39,0.23,-4.59
300,244,20.09,0.25,-3.31
400,244,20.01,0.25,-3.12
500,244,19.96,0.26,-3.06
600,244,19.93,0.26,-3.04
700,244,19.91,0.26,-3.02
800,244,19.88,0.26,-3.04
900,244,19.85,0.27,-3.02
1000,244,19.84,0.27,-3.03
,Count,RMSE,R2,Bias
0,244,25.95,-0.25,-17.99
100,244,23.79,-0.05,-12.91
200,244,20.55,0.21,-5.20
300,244,20.21,0.24,-3.92
400,244,20.11,0.25,-3.63
500,244,20.05,0.25,-3.53
600,244,20.01,0.25,-3.47
700,244,20.00,0.26,-3.43
800,244,19.99,0.26,-3.43
900,244,19.97,0.26,-3.42
1000,244,19.95,0.26,-3.41
,Count,RMSE,R2,Bias
0,244,26.04,-0.26,-17.96
100,244,29.66,-0.64,-21.98
200,244,22.82,0.03,-10.55
300,244,21.20,0.16,-5.87
400,244,20.80,0.19,-4.03
500,244,20.70,0.20,-3.32
600,244,20.66,0.21,-3.08
700,244,20.65,0.21,-2.98
800,244,20.64,0.21,-2.96
900,244,20.64,0.21,-2.94
1000,244,20.63,0.21,-2.93
,Count,RMSE,R2,Bias
0,244,26.00,-0.26,-17.91
100,244,29.11,-0.58,-20.95
200,244,22.69,0.04,-9.96
300,244,21.21,0.16,-5.47
400,244,20.86,0.19,-3.72
500,244,20.75,0.20,-3.06
600,244,20.72,0.20,-2.79
700,244,20.71,0.20,-2.70
800,244,20.70,0.20,-2.67
900,244,20.70,0.20,-2.67
1000,244,20.69,0.20,-2.65
,Count,RMSE,R2,Bias
0,244,25.88,-0.25,-17.83
100,244,28.30,-0.49,-19.66
200,244,22.61,0.05,-9.58
300,244,21.24,0.16,-5.49
400,244,20.89,0.19,-3.89
500,244,20.79,0.19,-3.29
600,244,20.76,0.20,-3.06
700,244,20.74,0.20,-2.97
800,244,20.74,0.20,-2.97
900,244,20.73,0.20,-2.90
1000,244,20.73,0.20,-2.94
,Count,RMSE,R2,Bias
0,244,25.80,-0.24,-17.83
100,244,27.40,-0.40,-18.25
200,244,22.47,0.06,-8.95
300,244,21.31,0.15,-5.13
400,244,21.02,0.18,-3.65
500,244,20.93,0.18,-3.09
600,244,20.90,0.19,-2.89
700,244,20.89,0.19,-2.82
800,244,20.88,0.19,-2.80
900,244,20.88,0.19,-2.81
1000,244,20.89,0.19,-2.83
,Count,RMSE,R2,Bias
0,244,25.77,-0.24,-17.67
100,244,25.84,-0.24,-15.95
200,244,21.83,0.11,-7.79
300,244,20.99,0.18,-4.40
400,244,20.79,0.19,-3.08
500,244,20.74,0.20,-2.58
600,244,20.73,0.20,-2.40
700,244,20.72,0.20,-2.34
800,244,20.72,0.20,-2.33
900,244,20.71,0.20,-2.32
1000,244,20.72,0.20,-2.33

In [26]:
preds2 = []
for test_preds in preds:
    temp = []
    for epoch in range(len(test_preds[0])):
        temp.append([])
        for run in range(len(test_preds)):
            temp[-1].append(test_preds[run][epoch])
    preds2.append(temp)

In [27]:
random_seed = 46524

In [28]:
y = preds_.y
full_stats = []
num_ensembles = 100
ensemble_size = 10
for test_preds in preds2:
    summ_stats = []
    ensembles, test_stats = generate_ensembles(test_preds, ensemble_runs=num_ensembles, ensemble_sizes=ensemble_size)
    for epoch_ in test_stats:
        summ_stats.append(pd.concat([x.loc['base'] for x in epoch_], axis=1)) #.mean(axis=1)
    full_stats.append(pd.concat(summ_stats, keys=pd.RangeIndex.from_range(range(0, 1001, 100))).mean(axis=1).unstack())

Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 10: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 10: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 10: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 10: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 10: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 10: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 10: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 10: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 10: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 10: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 10: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100

In [29]:
display_frames(full_stats, test_names[11:22], precision=2)

,Count,RMSE,R2,Bias
0,244.00,27.75,-0.47,-18.18
100,244.00,20.01,0.25,-3.95
200,244.00,20.01,0.25,-3.67
300,244.00,20.06,0.25,-3.61
400,244.00,20.04,0.25,-3.30
500,244.00,19.94,0.26,-3.32
600,244.00,19.94,0.26,-3.18
700,244.00,19.96,0.26,-3.26
800,244.00,19.95,0.26,-3.29
900,244.00,19.89,0.26,-3.15
1000,244.00,19.93,0.26,-3.13
,Count,RMSE,R2,Bias
0,244.00,27.76,-0.47,-18.23
100,244.00,19.81,0.27,-3.48
200,244.00,19.81,0.27,-3.01
300,244.00,19.87,0.26,-3.12
400,244.00,19.83,0.27,-3.06
500,244.00,19.74,0.27,-2.97
600,244.00,19.80,0.27,-3.17
700,244.00,19.82,0.27,-3.04
800,244.00,19.87,0.26,-3.27
900,244.00,19.72,0.28,-3.04
1000,244.00,19.81,0.27,-3.10
,Count,RMSE,R2,Bias
0,244.00,27.77,-0.47,-18.26
100,244.00,20.25,0.24,-4.68
200,244.00,20.15,0.24,-3.60
300,244.00,20.13,0.24,-3.58
400,244.00,20.06,0.25,-3.43
500,244.00,19.99,0.26,-3.40
600,244.00,20.04,0.25,-3.48
700,244.00,19.98,0.26,-3.27
800,244.00,20.07,0.25,-3.37
900,244.00,19.95,0.26,-3.20
1000,244.00,19.91,0.26,-3.12
,Count,RMSE,R2,Bias
0,244.00,27.86,-0.48,-18.44
100,244.00,21.19,0.16,-6.36
200,244.00,20.69,0.20,-3.73
300,244.00,20.69,0.20,-3.52
400,244.00,20.64,0.21,-3.37
500,244.00,20.46,0.22,-3.43
600,244.00,20.47,0.22,-3.55
700,244.00,20.48,0.22,-3.47
800,244.00,20.40,0.23,-3.54
900,244.00,20.37,0.23,-3.36
1000,244.00,20.41,0.22,-3.42
,Count,RMSE,R2,Bias
0,244.00,27.81,-0.48,-18.32
100,244.00,24.27,-0.10,-12.93
200,244.00,21.16,0.17,-4.66
300,244.00,20.92,0.19,-3.38
400,244.00,20.78,0.20,-2.97
500,244.00,20.66,0.21,-3.03
600,244.00,20.56,0.21,-3.09
700,244.00,20.57,0.21,-2.97
800,244.00,20.44,0.22,-2.99
900,244.00,20.36,0.23,-2.98
1000,244.00,20.45,0.22,-2.99
,Count,RMSE,R2,Bias
0,244.00,27.71,-0.47,-18.27
100,244.00,24.32,-0.10,-12.78
200,244.00,21.38,0.15,-5.31
300,244.00,21.01,0.18,-3.88
400,244.00,20.82,0.19,-3.54
500,244.00,20.66,0.20,-3.49
600,244.00,20.58,0.21,-3.56
700,244.00,20.58,0.21,-3.40
800,244.00,20.50,0.22,-3.49
900,244.00,20.41,0.22,-3.41
1000,244.00,20.56,0.21,-3.50
,Count,RMSE,R2,Bias
0,244.00,27.83,-0.48,-18.27
100,244.00,30.09,-0.69,-21.71
200,244.00,23.70,-0.05,-10.78
300,244.00,22.10,0.09,-5.84
400,244.00,21.63,0.13,-3.91
500,244.00,21.46,0.14,-3.29
600,244.00,21.40,0.15,-3.19
700,244.00,21.48,0.14,-2.98
800,244.00,21.28,0.16,-3.06
900,244.00,21.24,0.16,-2.99
1000,244.00,21.47,0.14,-2.86
,Count,RMSE,R2,Bias
0,244.00,27.80,-0.48,-18.23
100,244.00,29.56,-0.64,-20.71
200,244.00,23.55,-0.03,-10.13
300,244.00,22.10,0.09,-5.40
400,244.00,21.71,0.12,-3.63
500,244.00,21.54,0.14,-3.08
600,244.00,21.45,0.14,-2.87
700,244.00,21.52,0.14,-2.64
800,244.00,21.37,0.15,-2.77
900,244.00,21.33,0.15,-2.78
1000,244.00,21.51,0.14,-2.57
,Count,RMSE,R2,Bias
0,244.00,27.72,-0.47,-18.22
100,244.00,28.85,-0.56,-19.43
200,244.00,23.52,-0.03,-9.77
300,244.00,22.13,0.09,-5.42
400,244.00,21.81,0.11,-3.83
500,244.00,21.60,0.13,-3.27
600,244.00,21.56,0.13,-3.13
700,244.00,21.62,0.13,-2.87
800,244.00,21.43,0.14,-3.06
900,244.00,21.44,0.14,-3.07
1000,244.00,21.55,0.13,-2.95
,Count,RMSE,R2,Bias
0,244.00,27.64,-0.46,-18.22
100,244.00,27.84,-0.45,-17.87
200,244.00,23.40,-0.02,-9.11
300,244.00,22.19,0.08,-5.09
400,244.00,21.96,0.10,-3.62
500,244.00,21.72,0.12,-3.16
600,244.00,21.74,0.12,-3.00
700,244.00,21.77,0.12,-2.70
800,244.00,21.58,0.13,-2.85
900,244.00,21.63,0.13,-2.98
1000,244.00,21.70,0.12,-2.89
,Count,RMSE,R2,Bias
0,244.00,27.69,-0.46,-18.11
100,244.00,26.50,-0.31,-15.68
200,244.00,22.68,0.04,-7.94
300,244.00,22.06,0.09,-4.34
400,244.00,21.79,0.12,-3.05
500,244.00,21.61,0.13,-2.53
600,244.00,21.65,0.13,-2.52
700,244.00,21.65,0.13,-2.27
800,244.00,21.44,0.14,-2.43
900,244.00,21.48,0.14,-2.63
1000,244.00,21.48,0.14,-2.36

## Frozen Layers

In [30]:
preds = []
test_dirs = sort_file_list(glob.glob(os.path.join(model_dir, f'test*')), 'test')
for test_dir in test_dirs[22:]:
    test_preds = []
    run_dirs = sort_file_list(glob.glob(os.path.join(test_dir, f'run*')), 'run')
    for run_dir in run_dirs:
        run_preds = []
        epoch_dirs = sort_file_list(glob.glob(os.path.join(run_dir, f'epoch*')), 'epoch')
        for epoch_dir in epoch_dirs:
            preds_ = pd.read_csv(os.path.join(epoch_dir, 'test_predicts.csv'), index_col=0)
            run_preds.append(preds_)
        preds_ = pd.read_csv(os.path.join(run_dir, 'test_predicts.csv'), index_col=0)
        run_preds.append(preds_)
        test_preds.append(run_preds)
    preds.append(test_preds)

In [31]:
y = preds_.y
stats_dfs = []
for test_preds in preds: #[:num_ensembles]:
    summ_ = pd.concat([pd.concat([r.base for r in t], keys=pd.RangeIndex.from_range(range(0, 1001, 100))) for t in test_preds],
                      axis=1, ignore_index=True).mean(axis=1).unstack()
    stats_ = {epochs: calc_statistics(y, yhat[y.index]) for epochs, yhat in summ_.iterrows()}
    summ_stats = pd.DataFrame.from_dict(stats_, orient='index')
    stats_dfs.append(summ_stats)
display_frames(stats_dfs, test_names[22:], precision=2)

,Count,RMSE,R2,Bias
0,244,25.99,-0.26,-17.91
100,244,19.23,0.31,-2.76
200,244,19.08,0.32,-2.38
300,244,19.03,0.33,-2.20
400,244,19.05,0.32,-2.11
500,244,19.04,0.33,-2.12
600,244,19.05,0.32,-2.02
700,244,19.10,0.32,-2.15
800,244,19.13,0.32,-2.07
900,244,19.14,0.32,-2.13
1000,244,19.17,0.32,-2.22
,Count,RMSE,R2,Bias
0,244,26.01,-0.26,-17.95
100,244,19.23,0.31,-3.09
200,244,19.17,0.32,-2.25
300,244,19.24,0.31,-2.24
400,244,19.31,0.31,-2.29
500,244,19.38,0.30,-2.35
600,244,19.44,0.30,-2.41
700,244,19.47,0.29,-2.45
800,244,19.52,0.29,-2.48
900,244,19.55,0.29,-2.47
1000,244,19.57,0.29,-2.52
,Count,RMSE,R2,Bias
0,244,26.01,-0.26,-17.98
100,244,19.32,0.30,-3.52
200,244,19.21,0.31,-2.27
300,244,19.26,0.31,-2.29
400,244,19.29,0.31,-2.33
500,244,19.31,0.31,-2.33
600,244,19.33,0.30,-2.37
700,244,19.34,0.30,-2.37
800,244,19.35,0.30,-2.39
900,244,19.36,0.30,-2.41
1000,244,19.37,0.30,-2.41
,Count,RMSE,R2,Bias
0,244,26.11,-0.27,-18.16
100,244,19.77,0.27,-5.25
200,244,19.33,0.30,-2.72
300,244,19.33,0.30,-2.67
400,244,19.36,0.30,-2.68
500,244,19.38,0.30,-2.68
600,244,19.39,0.30,-2.68
700,244,19.42,0.30,-2.69
800,244,19.44,0.30,-2.68
900,244,19.46,0.30,-2.68
1000,244,19.48,0.29,-2.70
,Count,RMSE,R2,Bias
0,244,26.05,-0.26,-18.03
100,244,22.95,0.02,-11.96
200,244,20.07,0.25,-3.94
300,244,19.88,0.26,-2.73
400,244,19.85,0.27,-2.52
500,244,19.83,0.27,-2.51
600,244,19.82,0.27,-2.52
700,244,19.81,0.27,-2.54
800,244,19.81,0.27,-2.56
900,244,19.81,0.27,-2.57
1000,244,19.80,0.27,-2.60
,Count,RMSE,R2,Bias
0,244,25.95,-0.25,-17.99
100,244,22.94,0.02,-11.66
200,244,20.23,0.24,-4.23
300,244,19.97,0.26,-3.06
400,244,19.89,0.26,-2.84
500,244,19.85,0.27,-2.77
600,244,19.82,0.27,-2.77
700,244,19.80,0.27,-2.78
800,244,19.80,0.27,-2.80
900,244,19.79,0.27,-2.80
1000,244,19.78,0.27,-2.81
,Count,RMSE,R2,Bias
0,244,26.04,-0.26,-17.96
100,244,29.04,-0.57,-21.16
200,244,21.94,0.10,-9.38
300,244,20.47,0.22,-4.77
400,244,20.17,0.24,-3.02
500,244,20.09,0.25,-2.36
600,244,20.07,0.25,-2.12
700,244,20.07,0.25,-2.02
800,244,20.06,0.25,-2.00
900,244,20.06,0.25,-1.97
1000,244,20.06,0.25,-1.97
,Count,RMSE,R2,Bias
0,244,26.00,-0.26,-17.91
100,244,28.38,-0.50,-20.08
200,244,21.89,0.11,-9.03
300,244,20.51,0.22,-4.70
400,244,20.22,0.24,-3.04
500,244,20.14,0.24,-2.41
600,244,20.12,0.25,-2.19
700,244,20.12,0.25,-2.11
800,244,20.11,0.25,-2.06
900,244,20.10,0.25,-2.04
1000,244,20.11,0.25,-2.06
,Count,RMSE,R2,Bias
0,244,25.88,-0.25,-17.83
100,244,27.64,-0.42,-19.05
200,244,21.69,0.12,-8.51
300,244,20.48,0.22,-4.39
400,244,20.23,0.24,-2.82
500,244,20.17,0.24,-2.23
600,244,20.15,0.24,-2.01
700,244,20.14,0.24,-1.93
800,244,20.14,0.24,-1.90
900,244,20.14,0.24,-1.90
1000,244,20.14,0.24,-1.89
,Count,RMSE,R2,Bias
0,244,25.80,-0.24,-17.83
100,244,26.67,-0.32,-17.69
200,244,21.46,0.14,-8.14
300,244,20.40,0.23,-4.39
400,244,20.18,0.24,-2.96
500,244,20.12,0.25,-2.43
600,244,20.11,0.25,-2.23
700,244,20.10,0.25,-2.16
800,244,20.10,0.25,-2.14
900,244,20.09,0.25,-2.12
1000,244,20.09,0.25,-2.15
,Count,RMSE,R2,Bias
0,244,25.77,-0.24,-17.67
100,244,24.92,-0.16,-15.47
200,244,20.79,0.19,-7.19
300,244,19.98,0.26,-3.89
400,244,19.82,0.27,-2.63
500,244,19.79,0.27,-2.15
600,244,19.78,0.27,-1.98
700,244,19.77,0.27,-1.92
800,244,19.77,0.27,-1.90
900,244,19.77,0.27,-1.92
1000,244,19.77,0.27,-1.92

In [32]:
preds2 = []
for test_preds in preds:
    temp = []
    for epoch in range(len(test_preds[0])):
        temp.append([])
        for run in range(len(test_preds)):
            temp[-1].append(test_preds[run][epoch])
    preds2.append(temp)

In [33]:
random_seed = 46524

In [34]:
y = preds_.y
full_stats = []
num_ensembles = 100
ensemble_size = 10
for test_preds in preds2:
    summ_stats = []
    ensembles, test_stats = generate_ensembles(test_preds, ensemble_runs=num_ensembles, ensemble_sizes=ensemble_size)
    for epoch_ in test_stats:
        summ_stats.append(pd.concat([x.loc['base'] for x in epoch_], axis=1)) #.mean(axis=1)
    full_stats.append(pd.concat(summ_stats, keys=pd.RangeIndex.from_range(range(0, 1001, 100))).mean(axis=1).unstack())

Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 10: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 10: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 10: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 10: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 10: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 10: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 10: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 10: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 10: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 10: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 0: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 1: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 2: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 3: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 4: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 5: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 6: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 7: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 8: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 9: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100
Generating ensembles - test 10: .........10.........20.........30.........40.........50.........60.........70.........80.........90.........100

In [35]:
display_frames(full_stats, test_names[22:], precision=2)

,Count,RMSE,R2,Bias
0,244.00,27.75,-0.47,-18.18
100,244.00,19.80,0.27,-2.79
200,244.00,19.89,0.26,-2.51
300,244.00,19.89,0.26,-2.40
400,244.00,19.85,0.27,-2.17
500,244.00,19.68,0.28,-2.13
600,244.00,19.68,0.28,-2.10
700,244.00,19.74,0.27,-2.17
800,244.00,19.74,0.27,-2.10
900,244.00,19.61,0.28,-2.08
1000,244.00,19.75,0.27,-2.15
,Count,RMSE,R2,Bias
0,244.00,27.76,-0.47,-18.23
100,244.00,19.85,0.27,-3.11
200,244.00,20.01,0.25,-2.29
300,244.00,20.06,0.25,-2.29
400,244.00,20.06,0.25,-2.21
500,244.00,20.05,0.25,-2.31
600,244.00,20.12,0.25,-2.54
700,244.00,20.11,0.25,-2.41
800,244.00,20.10,0.25,-2.65
900,244.00,20.09,0.25,-2.55
1000,244.00,20.20,0.24,-2.53
,Count,RMSE,R2,Bias
0,244.00,27.77,-0.47,-18.26
100,244.00,19.96,0.26,-3.57
200,244.00,20.11,0.25,-2.31
300,244.00,20.13,0.24,-2.34
400,244.00,20.07,0.25,-2.29
500,244.00,20.00,0.25,-2.38
600,244.00,19.95,0.26,-2.45
700,244.00,19.98,0.26,-2.39
800,244.00,19.94,0.26,-2.52
900,244.00,19.86,0.27,-2.44
1000,244.00,19.91,0.26,-2.32
,Count,RMSE,R2,Bias
0,244.00,27.86,-0.48,-18.44
100,244.00,20.44,0.22,-5.24
200,244.00,20.18,0.24,-2.82
300,244.00,20.25,0.24,-2.69
400,244.00,20.16,0.24,-2.61
500,244.00,20.03,0.25,-2.64
600,244.00,20.06,0.25,-2.81
700,244.00,20.11,0.25,-2.79
800,244.00,20.03,0.25,-2.84
900,244.00,19.91,0.26,-2.69
1000,244.00,20.08,0.25,-2.74
,Count,RMSE,R2,Bias
0,244.00,27.81,-0.48,-18.32
100,244.00,23.61,-0.04,-11.91
200,244.00,20.91,0.18,-4.04
300,244.00,20.84,0.19,-2.85
400,244.00,20.66,0.20,-2.41
500,244.00,20.57,0.21,-2.48
600,244.00,20.49,0.22,-2.64
700,244.00,20.48,0.22,-2.59
800,244.00,20.43,0.22,-2.66
900,244.00,20.32,0.23,-2.55
1000,244.00,20.50,0.22,-2.51
,Count,RMSE,R2,Bias
0,244.00,27.71,-0.47,-18.27
100,244.00,23.57,-0.04,-11.56
200,244.00,21.06,0.17,-4.35
300,244.00,20.86,0.19,-3.14
400,244.00,20.62,0.21,-2.77
500,244.00,20.51,0.22,-2.68
600,244.00,20.44,0.22,-2.88
700,244.00,20.37,0.23,-2.84
800,244.00,20.32,0.23,-2.93
900,244.00,20.28,0.23,-2.90
1000,244.00,20.42,0.22,-2.71
,Count,RMSE,R2,Bias
0,244.00,27.83,-0.48,-18.27
100,244.00,29.66,-0.65,-21.02
200,244.00,22.89,0.02,-9.61
300,244.00,21.52,0.14,-4.89
400,244.00,21.06,0.17,-2.85
500,244.00,20.95,0.18,-2.27
600,244.00,20.84,0.19,-2.26
700,244.00,20.90,0.19,-2.10
800,244.00,20.77,0.20,-2.21
900,244.00,20.71,0.20,-2.06
1000,244.00,20.97,0.18,-1.83
,Count,RMSE,R2,Bias
0,244.00,27.80,-0.48,-18.23
100,244.00,28.97,-0.57,-19.89
200,244.00,22.84,0.03,-9.24
300,244.00,21.56,0.13,-4.76
400,244.00,21.12,0.17,-2.89
500,244.00,21.00,0.18,-2.36
600,244.00,20.87,0.19,-2.34
700,244.00,20.99,0.18,-2.18
800,244.00,20.85,0.19,-2.22
900,244.00,20.78,0.19,-2.14
1000,244.00,21.01,0.18,-1.97
,Count,RMSE,R2,Bias
0,244.00,27.72,-0.47,-18.22
100,244.00,28.31,-0.50,-18.94
200,244.00,22.66,0.04,-8.74
300,244.00,21.58,0.13,-4.46
400,244.00,21.15,0.17,-2.67
500,244.00,21.02,0.18,-2.16
600,244.00,20.93,0.18,-2.17
700,244.00,20.99,0.18,-1.95
800,244.00,20.88,0.19,-2.09
900,244.00,20.82,0.19,-1.97
1000,244.00,21.05,0.17,-1.81
,Count,RMSE,R2,Bias
0,244.00,27.64,-0.46,-18.22
100,244.00,27.27,-0.39,-17.41
200,244.00,22.47,0.06,-8.38
300,244.00,21.47,0.14,-4.40
400,244.00,21.15,0.17,-2.93
500,244.00,20.94,0.18,-2.42
600,244.00,20.87,0.19,-2.32
700,244.00,20.96,0.18,-2.11
800,244.00,20.87,0.19,-2.26
900,244.00,20.81,0.19,-2.23
1000,244.00,21.03,0.18,-2.13
,Count,RMSE,R2,Bias
0,244.00,27.69,-0.46,-18.11
100,244.00,25.69,-0.24,-15.13
200,244.00,21.86,0.11,-7.48
300,244.00,21.19,0.16,-3.84
400,244.00,20.85,0.19,-2.61
500,244.00,20.72,0.20,-1.98
600,244.00,20.64,0.21,-2.15
700,244.00,20.75,0.20,-1.95
800,244.00,20.60,0.21,-2.03
900,244.00,20.55,0.21,-2.14
1000,244.00,20.72,0.20,-1.93